version: '3.7'
services:
  mongo:
    image: 'mvertes/alpine-mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'
  server:
    container_name: 'server'
    build:
      context: '.'
      dockerfile: './cmd/server/Dockerfile'
    environment:
      - PORT=5000
      - MONGODB_URI=mongo:27017
      - MONGODB_NAME=go-e2ee-chat-engine
    ports:
      - '5000:5000'
    depends_on:
      - 'mongo'
